POST http://localhost:8080/games
Content-Type: application/json

{
  "playerName": "Tommy",
  "fieldOfStudy": "Wirtschaftsinformatik"
}

###

GET http://localhost:8080/games/1

###

POST http://localhost:8080/games
Content-Type: application/json

{
  "playerName": "",
  "fieldOfStudy": "   "
}

###

GET http://localhost:8080/games/10000000000

###

POST http://localhost:8080/games/1/modules
Content-Type: application/json

{
  "selectedStudyModuleIds": [1, 2]
}

###

GET http://localhost:8080/study-modules

###

GET http://localhost:8080/fields-of-study

###

GET http://localhost:8080/fields-of-study/3/modules