POST http://localhost:8080/games
Content-Type: application/json

{
  "playerName": "Tommy",
  "fieldOfStudy": "Wirtschaftsinformatik"
}

###

POST http://localhost:8080/games
Content-Type: application/json

{
  "playerName": "",
  "fieldOfStudy": "   "
}

###

GET http://localhost:8080/games/1

###

GET http://localhost:8080/games/10000000000